//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_TiendaAnimal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracteristicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caracteristicas()
        {
            this.nexo = new HashSet<nexo>();
        }
    
        public string edad { get; set; }
        public string raza { get; set; }
        public string codigo_ean { get; set; }
        public string cuidado_especifico { get; set; }
        public string opcion_nutricional { get; set; }
        public int id_caracteristicas { get; set; }
        public string ingrediente_principal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nexo> nexo { get; set; }
    }
}
