//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_TiendaAnimal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class descripciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public descripciones()
        {
            this.nexo = new HashSet<nexo>();
        }
    
        public string ingrediente { get; set; }
        public string constituyente_analticos { get; set; }
        public string mineral { get; set; }
        public string vitamina { get; set; }
        public string energia_metabolizante { get; set; }
        public string aditivos_tecnologicos { get; set; }
        public int id_descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nexo> nexo { get; set; }
    }
}
