//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_TiendaAnimal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TiendaAnimalDataEntities1 : DbContext
    {
        public TiendaAnimalDataEntities1()
            : base("name=TiendaAnimalDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caracteristicas> caracteristicas { get; set; }
        public virtual DbSet<descripciones> descripciones { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<nexo> nexo { get; set; }
    }
}
